### ISSUE TITLE
Escopo do produto, cronograma das atividades

### ISSUE THREAD

**Issue by Edilson-Gomes** [Francielefernandes06/documentacao-projeto-coorporativo-2024.2#24]
## **Sistema Protocolar CityHub**
**Objetivo:** Desenvolver um sistema protocolar que centralize a criação, o acompanhamento e a comunicação de requisições entre cidadãos e os departamentos municipais, promovendo transparência e eficiência no atendimento.
#### **Documentos inicias necessários**
- Escopo do produto;
- EAP - Estrutura Analítica do Projeto
- Estimativas de esforço e custo
- Cronograma (Gantt e Atividades)
- Versão parcial do produto (protótipos).

**Comment by Francielefernandes06** [comment]
O planejamento detalhado do Escopo do Produto - Sistema Protocolar CityHub foi criado e está disponível no seguinte link: [Acessar Planejamento do Escopo do Produto](https://github.com/users/Francielefernandes06/projects/3/views/1?pane=issue&itemId=90025500&issue=Francielefernandes06%7Cdocumentacao-projeto-coorporativo-2024.2%7C27).

**Comment by Edilson-Gomes** [comment]
Revisei a tarefa e está tudo certo para mim. 👍
Podemos prosseguir conforme o planejado!
