### ISSUE TITLE
Relatório para testes

### ISSUE THREAD

**Issue by Edilson-Gomes** [Francielefernandes06/documentacao-projeto-coorporativo-2024.2#25]
**Assim que o projeto estiver definido:**
- ○ Planejamento de Teste de cenário para o projeto
- ○ Teste de cenário para o projeto
- ○ Casos de testes das três principais funcionalidades do sistema.

**Use como referência:**
- [Requisitos Funcionais](./documentos/Requisitos-Funcionais-CityHub.md)
- [Requisitos Não Funcionais](./documentos/Requisitos-Funcionais-CityHub.md)
- [Regras de Negócios](./documentos/Regras-de-Negócios-CityHub.md)
- [Diagrama de Caso de uso](./imagens/Diagrama-Caso-de-Uso.png)
- [Diagrama de Classe](./diagramas/Diagrama-Classes.md)
- [Diagrama de Fluxo de Eventos](./diagramas/Diagrama-Fluxo-Eventos.md)

**Comment by Francielefernandes06** [comment]
@Edilson-Gomes 

Segue o merge para aprovação:
https://github.com/Francielefernandes06/documentacao-projeto-coorporativo-2024.2/pull/29

**Comment by Edilson-Gomes** [comment]
É necessário fazer alterações nesse planejamento de testes.
