### ISSUE TITLE
Planejamento do Desenvolvimento do Escopo do Produto

### ISSUE THREAD

**Issue by Francielefernandes06** [Francielefernandes06/documentacao-projeto-coorporativo-2024.2#27]
**Fase**:  Planejamento
**Descrição:**

Nessa etapa, o planejamento será voltado para definir como o sistema CityHub vai ser desenvolvido e entregue, considerando as funcionalidades principais, o que o sistema deve ou não fazer, e como garantir que ele atenda aos objetivos de transparência e eficiência no atendimento.

O processo inclui:

- Definir o que é mais importante entregar primeiro, pensando no impacto e na viabilidade.
- Estimar o esforço e o tempo necessário para cada funcionalidade.
- Alinhar prazos e criar um cronograma geral.
- Organizar os recursos necessários, seja pessoal, tecnologia ou orçamento.

**Resultado Esperado:**

Escopo do Produto: 
o Documento terá:
1. **Alinhamento de Expectativas**

- Deixar claro para todos os envolvidos o que esperar em cada entrega, incluindo limites de prazo e recursos.

2. **Objetivos do Sistema**
3. **Descrição das Funcionalidades**
4. **Escopo Fora do Projeto (O que não será desenvolvido)**
5. **Público-Alvo e Usuários do Sistema**
6. **Recursos Necessários**

**Comment by Edilson-Gomes** [comment]
<html>
<body>
<html><head></head><body><p>Taxas específicas de custos, papéis principais envolvidos em cada tarefa:</p>
<ul>
<li><strong>Desenvolvedor</strong>: R$ 18/h</li>
<li><strong>Testador</strong>: R$ 14/h</li>
<li><strong>Analista de Negócios</strong>: R$ 22/h</li>
</ul>
<p>Para cada tarefa, definimos a distribuição aproximada do esforço por papel:</p>
<ul>
<li><strong>Planejamento e design</strong>: 80% analista, 20% desenvolvedor.</li>
<li><strong>Desenvolvimento</strong>: 90% desenvolvedor, 10% testador.</li>
<li><strong>Testes</strong>: 100% testador.</li>
<li><strong>Documentação e ajustes</strong>: 60% analista, 40% desenvolvedor.</li>
</ul>
<h3>Estimativa de esforço e custo:</h3>

Sprint | Tarefa | Esforço (horas) | Custo (R$)
-- | -- | -- | --
Sprint 1: Planejamento e Design Inicial | Refinamento do backlog do produto | 40 | 704 (80% analista, 20% dev)
  | Criação de wireframes e protótipos | 32 | 563 (80% analista, 20% dev)
  | Configuração inicial de ambiente | 40 | 720 (100% dev)
  | Definição de critérios de aceitação | 48 | 845 (80% analista, 20% dev)
  | Subtotal Sprint 1 | 160 | R$ 2.832
Sprint 2: Módulo de Gestão de Protocolos | Desenvolvimento de formulários | 56 | 1.008 (90% dev, 10% test)
  | Sistema de categorização e identificadores únicos | 48 | 864 (90% dev, 10% test)
  | Testes unitários e ajustes | 40 | 560 (100% test)
  | Subtotal Sprint 2 | 144 | R$ 2.432
Sprint 3: Portal do Cidadão | Módulo de distribuição interna | 56 | 1.008 (90% dev, 10% test)
  | Notificações e interface do portal | 48 | 864 (90% dev, 10% test)
  | Testes de integração | 40 | 560 (100% test)
  | Subtotal Sprint 3 | 144 | R$ 2.432
Sprint 4: Status, Relatórios e Autenticação | Atualização de status e relatórios | 48 | 844 (80% analista, 20% dev)
  | Autenticação e perfis de usuários | 40 | 720 (100% dev)
  | Testes de segurança | 40 | 560 (100% test)
  | Subtotal Sprint 4 | 128 | R$ 2.124
Sprint 5: Finalização e Documentação | Testes gerais e ajustes finais | 40 | 560 (100% test)
  | Documentação técnica | 40 | 704 (60% analista, 40% dev)
  | Preparação para o deploy | 40 | 720 (100% dev)
  | Subtotal Sprint 5 | 120 | R$ 1.984
TOTAL GERAL: |   | 696 horas | R$ 11.804


<hr>
<h3><strong>Distribuição dos custos por papel:</strong></h3>
<ul>
<li><strong>Desenvolvedor (R$ 18/h)</strong>: R$ 7.200 (400 horas).</li>
<li><strong>Testador (R$ 14/h)</strong>: R$ 2.380 (170 horas).</li>
<li><strong>Analista de Negócios (R$ 22/h)</strong>: R$ 2.224 (126 horas).</li>
</ul>
<p>Divisão das atividades e custos para cada papel.</p></body></html>
</body>
</html>

**Comment by Francielefernandes06** [comment]
@Edilson-Gomes 

Aprovado, pode seguir no desenvolvimento do documento.

Aguardado o merge!
